### PR TITLE
Duplicated user agent groups merge

### PR DESCRIPTION
**Pull request by sergebezborodov**
Hello!

Thank you for your library. I found at some websites user agent groups are duplicated.
For example:
```
# Added by SEO Ultimate's Link Mask Generator module
User-agent: *
Disallow: /go/
# End Link Mask Generator output

User-agent: *
Disallow: /wp-admin/
Disallow: /?s=
```
In this case FindGroup finds only first group and returns wrong result.
Please see my changes.

thank you

### CODE REVIEW

**Comment by temoto** [comment]
Hello, Serge.

Thanks for your report and especially for patch. I agree this is a problem. I do not agree with solution.

I'm uploading alternative version soon. Your contribution is appreciated still.

**Comment by sergebezborodov** [comment]
hello temoto, will wait for your solution, I'm new in golang

**Comment by temoto** [comment]
Initially I thought it'd be better to create `map[useragent string]Group` for faster than two loop lookups. Spent two hours on rewrite only to realise it's impossible, because one-to-many useragent-group relation.

So I thought OK, let's extract `findGroupByUA` to module level function and merge your code.

But then I realised it will also break in following case:
```
useragent: A
useragent: B
disallow: /a
disallow: /b

useragent: ignore-it
disallow: /ignore-it

useragent: A
disallow: /c   # this must not apply to agent B
```

Have to work on this more.

**Comment by temoto** [comment]
Had to rewrite a lot, parser now creates separate `Group` for each user-agent, even for sibling.

**Comment by sergebezborodov** [comment]
thank you, will test the new version in my crawler

**Comment by temoto** [comment]
Is it open source?

**Comment by temoto** [comment]
Fix is merged in master 9e4646fa705336d5b2fa9dddfafbe0a1a965acd7

**Pull request closed without merging**
